name: build-docker
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-prod-image:
    name: Build try.tarantool.io image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Download Tarantool
      run: |
        curl -L https://${{ secrets.TARANTOOL_IO_USER }}:${{ secrets.TARANTOOL_IO_TOKEN }}@download.tarantool.io/enterprise/tarantool-enterprise-bundle-${{ secrets.BUNDLE_VERSION }}.tar.gz -o tarantool-enterprise-bundle-${{ secrets.BUNDLE_VERSION }}.tar.gz
    - name: Install tarantool
      run: |
        tar -xzf tarantool-enterprise-bundle-${{ secrets.BUNDLE_VERSION }}.tar.gz
        echo "SDK_PATH=${PWD}/tarantool-enterprise" >> $GITHUB_ENV
    - name: Set PATH
      run: echo ${{ env.SDK_PATH }} >> $GITHUB_PATH

    - name: pack docker image
      run: |
        cartridge pack docker --tag cartridge-app:${{ env.RELEASE_VERSION }} --sdk-path=${{ env.SDK_PATH }}

    - name: Docker login
      uses: docker/login-action@v1
      with:
        registry: ${{ secrets.DOCKER_REGISTRY }}
        username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
        password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Tag docker image
      run: |
        docker tag cartridge-app:${{ env.RELEASE_VERSION }} ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:${{ env.RELEASE_VERSION }}-0
        docker tag cartridge-app:${{ env.RELEASE_VERSION }} ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:latest
    - name: Push docker image
      run: |
        docker push ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:${{ env.RELEASE_VERSION }}-0
        docker push ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:latest

  build-public-image:
    name: Build public tarantool/getting-started image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2

    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Set up the Tarantool packages repository
      run: curl -L https://tarantool.io/installer.sh | sudo -E bash -s -- --repo-only

    - name: Install tarantool
      run: |
        sudo apt install tarantool

    - name: Install cartridge-cli
      run: |
        sudo apt install cartridge-cli

    - name: pack docker image
      run: |
        cartridge pack docker --tag cartridge-app:${{ env.RELEASE_VERSION }}

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag docker image
      run: |
        docker tag cartridge-app:${{ env.RELEASE_VERSION }} ghcr.io/tarantool/getting-started:${{ env.RELEASE_VERSION }}
        docker tag cartridge-app:${{ env.RELEASE_VERSION }} ghcr.io/tarantool/getting-started:latest

    - name: Push docker image
      run: |
        docker push ghcr.io/tarantool/getting-started:${{ env.RELEASE_VERSION }}
        docker push ghcr.io/tarantool/getting-started:latest
