name: build-docker
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-image:
    runs-on: [self-hosted]
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: pack docker image
      run: |
        cartridge pack docker --tag cartridge-app:${{ env.RELEASE_VERSION }} --sdk-path=$HOME/tarantool-enterprise/

  push-docker:
    runs-on: [self-hosted]
    needs: build-image
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Docker login
      run: docker login ${{ secrets.DOCKER_REGISTRY }} --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag docker image
      run: docker tag cartridge-app:${{ env.RELEASE_VERSION }} ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:${{ env.RELEASE_VERSION }}-0
    - name: Push docker image
      run: docker push ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:${{ env.RELEASE_VERSION }}-0

  bench-push-docker:
    runs-on: [self-hosted, minikube]
    needs: build-image
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        token: ${{ secrets.SUBMODULE_K8S_SDK_TOKEN }}
    - name: Docker login
      run: docker login ${{ secrets.DOCKER_TEST_REGISTRY }} --username ${{ secrets.DOCKER_TEST_REGISTRY_USERNAME }} --password ${{ secrets.DOCKER_TEST_REGISTRY_PASSWORD }}
    - name: Tag docker image
      run: docker tag try-cartridge-backend:latest ${{ secrets.DOCKER_TEST_REGISTRY }}/try-cartridge-backend:latest
    - name: Push docker image
      run: docker push ${{ secrets.DOCKER_TEST_REGISTRY }}/try-cartridge-backend:latest
