name: build-docker
on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-image:
    runs-on: [self-hosted]
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: pack docker image
      run: |
        cartridge pack docker --tag cartridge-app:${{ env.RELEASE_VERSION }} --sdk-path=$HOME/tarantool-enterprise/

  push-docker:
    runs-on: [self-hosted]
    needs: build-image
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Docker login
      run: docker login ${{ secrets.DOCKER_REGISTRY }} --username ${{ secrets.DOCKER_REGISTRY_USERNAME }} --password ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
    - name: Tag docker image
      run: |
        docker tag cartridge-app:${{ env.RELEASE_VERSION }} ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:${{ env.RELEASE_VERSION }}-0 &&
        docker tag cartridge-app:latest ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:latest
    - name: Push docker image
      run: |
        docker push ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:${{ env.RELEASE_VERSION }}-0
        docker push ${{ secrets.DOCKER_REGISTRY }}/cartridge-app:latest
