name: build-docker
on:
  push:

jobs:
  build-image:
    runs-on: [self-hosted]
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: pack docker image
      run: |
        cartridge pack docker --tag cartridge-app:${{ env.RELEASE_VERSION }} --sdk-path=$HOME/tarantool-enterprise/

  push-docker:
    runs-on: [self-hosted]
    needs: build-image
    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Docker login
      run: docker login 5.188.142.162:5000 --username ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
    - name: Tag docker image
      run: docker tag cartridge-app:${{ env.RELEASE_VERSION }} 5.188.142.162:5000/cartridge-app:${{ env.RELEASE_VERSION }}-0
    - name: Push docker image
      run: docker push 5.188.142.162:5000/cartridge-app:${{ env.RELEASE_VERSION }}-0
